MONGODB_HOST: mongodb-{{ env }}.practicedev.shop # mongodb-dev.practicedev.shop
REDIS_HOST: redis-{{ env }}.practicedev.shop
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.practicedev.shop
CART_HOST: cart.backend-alb-{{ env }}.practicedev.shop
USER_HOST: user.backend-alb-{{ env }}.practicedev.shop
RABBITMQ_HOST: rabbitmq-{{ env }}.practicedev.shop
MYSQL_HOST: mysql-{{ env }}.practicedev.shop
SHIPPING_HOST: shipping.backend-alb-{{ env }}.practicedev.shop
PAYMENT_HOST: payment.backend-alb-{{ env }}.practicedev.shop